### ISSUE TITLE
IDEAS for TRND

### ISSUE THREAD

**Issue by DLAX11** [jwilld/fashion-site#3]
TRND logo color 
'black' and ' white'
Some how implant a moving NAV bar
also do "transition " when u scroll up and down the picture will be turning grey.
add API "google maps" to see where other models/photograpers are posting from 
make website/app for models and photographs but with a strong sense for models 
basically a instagram for models 
lets stay away from the instagram UI
whole point of white/black/grey UI so the models/photogrphers content will light up the app/ website with colors etc.
let the nav bar etc be colors when u touch them 
clean smooth modern UI that's what we chasing 
market to generation z but its for anybody but targeting the Z.
models can post their content/pics and add a 'follow' so other models/ photographs can follow other models have a bio for each profile. this app/ website will be the "middle man" to connect photographers and models also to have fun, position their content. 
uploading pics will be a breeze make it simple
models/photographers can send a 'trnd' to somebody else that will know somebody wants to work with them 
"trnd" will "equal" a instagram" like"
or have colors like tinder website 
more ideas will be coming
also lets go for a modern. retro . clean look easy to use

**Comment by jwilld** [comment]
Send me an example of the scrolling navigation bar?

**Comment by DLAX11** [comment]
yea once the person sends me the example but the code for it I will add the link below
https://codepen.io/dallalin2/pen/LYYPKvj
that's the 1 example, I will add my example when I get the link

**Comment by DLAX11** [comment]
another link of the nav bar im trying to create is this example right here 
https://sei-dc.slack.com/archives/DP36P4AKY/p1571920351000300
https://git.generalassemb.ly/DallasL/WebsitePractice
